// <auto-generated />
namespace MovieVault.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class inchallah3ad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inchallah3ad));
        
        string IMigrationMetadata.Id
        {
            get { return "201501111615045_inchallah3ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
